services:
  minigame-bot:
    container_name: minigame-bot
    build:
      context: ./apps/bot
    volumes:
    - ./app/dist:/apps/bot/dist
    env_file:
      - stack.env

  minigame-website:
    build:
      context: ./apps/web
    container_name: minigame-website
    ports:
      - 2081:2081

  minigame-api:
    build:
      context: ./apps/api
    container_name: minigame-api
    env_file:
      - stack.env
    volumes:
      - ./app/dist:/apps/api/dist
    ports:
      - 28001:28001
